// Centralized icon registry — named imports so Vite tree-shakes to ONLY these
// icons instead of bundling the entire lucide library (~128 kB gzip -> a few kB).
// Access is via a Proxy so BOTH `icons.Name` and dynamic `icons[dataDrivenName]`
// work, and any unknown name degrades gracefully to a Circle instead of crashing.
import {
  Activity,
  AlertCircle,
  AlignLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  Bell,
  BookMarked,
  BookOpen,
  BrainCircuit,
  Briefcase,
  CalendarClock,
  CalendarDays,
  CalendarOff,
  CalendarRange,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Component,
  Copy,
  Database,
  Download,
  Eye,
  EyeOff,
  FileQuestion,
  FileText,
  FileType,
  Fingerprint,
  Flame,
  FlaskConical,
  Globe,
  GraduationCap,
  Hash,
  Heart,
  Hourglass,
  Info,
  LayoutDashboard,
  LayoutList,
  List,
  ListChecks,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessagesSquare,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  PartyPopper,
  PenLine,
  PenTool,
  Pencil,
  Play,
  PlayCircle,
  Plus,
  Presentation,
  Printer,
  Radio,
  RefreshCw,
  RotateCcw,
  Save,
  ScanLine,
  Search,
  SearchX,
  Send,
  Share,
  ShieldCheck,
  Sparkles,
  Square,
  SquarePlus,
  Star,
  Sun,
  Target,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserCheck,
  UserPlus,
  Users,
  Video,
  Volume2,
  VolumeX,
  X,
} from 'lucide-vue-next'

const registry = {
  Activity, AlertCircle, AlignLeft, ArrowRight, ArrowUpRight, Award, Bell, BookMarked, BookOpen, BrainCircuit, Briefcase, CalendarClock, CalendarDays, CalendarOff, CalendarRange, Check, CheckCheck, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, ClipboardCheck, ClipboardList, Clock, Component, Copy, Database, Download, Eye, EyeOff, FileQuestion, FileText, FileType, Fingerprint, Flame, FlaskConical, Globe, GraduationCap, Hash, Heart, Hourglass, Info, LayoutDashboard, LayoutList, List, ListChecks, Loader2, Lock, LogOut, Mail, MapPin, Megaphone, Menu, MessageCircle, MessagesSquare, Moon, PanelLeftClose, PanelLeftOpen, PartyPopper, PenLine, PenTool, Pencil, Play, PlayCircle, Plus, Presentation, Printer, Radio, RefreshCw, RotateCcw, Save, ScanLine, Search, SearchX, Send, Share, ShieldCheck, Sparkles, Square, SquarePlus, Star, Sun, Target, Trash2, TrendingUp, Trophy, Upload, User, UserCheck, UserPlus, Users, Video, Volume2, VolumeX, X,
}

export const icons = new Proxy(registry, {
  get(target, key) {
    if (typeof key === 'string') {
      if (key in target) return target[key]
      if (/^[A-Z]/.test(key)) return target.Circle // unknown icon name -> safe fallback
    }
    return target[key]
  },
  has(target, key) { return typeof key === 'string' && /^[A-Z]/.test(key) ? true : key in target },
})

export default icons
